---
name: Cleanup
on:
  workflow_dispatch:
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
    # > Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs.
    # > High load times include the start of every hour. To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
    - cron: "48 5 * * *"

jobs:
  docker:
    name: Docker
    timeout-minutes: 10

    runs-on: ubuntu-24.04

    steps:
      - name: Delete old images
        uses: actions/delete-package-versions@v5
        with:
          package-name: golang-tip
          package-type: container
          min-versions-to-keep: 365
          delete-only-untagged-versions: true
