---
name: TarGz
on:
  schedule:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#scheduled-events
    # > Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs.
    # > High load times include the start of every hour. To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
    - cron: '48 2 * * *'
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    timeout-minutes: 15

    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-20.04
          - macos-10.15
        branch:
          - master
          - dev.boringcrypto
          - dev.fuzz
          - dev.go2go

    runs-on: ${{ matrix.os }}

    env:
      GO_BRANCH: ${{ matrix.branch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build .tar.gz file
        run: make targz-build

      # skip push for PRs
      - name: Upload .tar.gz file
        run: |
          mv golang-tip.tar.gz golang-tip.$(go env GOOS)-$(go env GOARCH).tar.gz
          ls -al
